### ISSUE TITLE
Unable to compile your project

### ISSUE THREAD

**Issue by abhi-uoh** [harish123098/TwitterHashTags-Top10#1]
Here is the list of error I am getting!

java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0xcd8b94a) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0xcd8b94a

![Screenshot 2021-04-16 at 11 35 25 AM](https://user-images.githubusercontent.com/55594873/114979060-d8441680-9ea7-11eb-8ef5-bbaf721e6b73.png)

**Comment by harish123098** [comment]
Hi @abhi-uoh , Please download lombok from plugins  if use intellje ide and restrat ide ,and try again.its Lombok dependency doesn't exist in system.

**Comment by harish123098** [comment]
Lombok will resolve the issue
